In [45]:
import numpy as np
import os 
import json
import random


def load_json(data_path):
    with open(data_path,'r') as rdata:
        motor_position_list = json.load(rdata)
    motor_position_list = motor_position_list['data']
    position, motor_control = [],[]
    for motor_position_dict in motor_position_list:
        motor_control.append(motor_position_dict['actuation'])
        position.append(motor_position_dict['position'])
    
    position = np.array(position, dtype=np.float32)
    motor_control = np.array(motor_control, dtype=np.float32)
    
    assert len(position) == len(motor_control)
    return motor_control, position


## ABAQUS

In [46]:
seed = 0
np.random.seed(seed)
random.seed(seed)

In [47]:
from pathlib import Path
DATA_PATH =  Path("dataset/ABAQUS_DATASET")
train_motor_control, train_position = load_json(DATA_PATH / "AbaqusTrain.json")
val_motor_control, val_position = load_json(DATA_PATH / "AbaqusValidate.json")
test_motor_control, test_position = load_json(DATA_PATH / "AbaqusTest.json")


In [48]:
motor_control = np.concatenate((train_motor_control, val_motor_control, test_motor_control), axis=0)
position = np.concatenate((train_position, val_position, test_position), axis=0)

motor_control.shape, position.shape

((5644, 3), (5644, 7, 3))

In [49]:
int_ratio = 0.7
sort_idx = np.argsort(np.linalg.norm(motor_control, axis=1))


int_idx = sort_idx[:int(sort_idx.shape[0]*int_ratio)]
ext_idx =sort_idx[int(sort_idx.shape[0]*int_ratio):]
random.shuffle(int_idx)
random.shuffle(ext_idx)

int_idx.shape, ext_idx.shape

((3950,), (1694,))

In [50]:
train_motor_control = motor_control[int_idx[:int(int_idx.shape[0]*0.8)]]
train_position = position[int_idx[:int(int_idx.shape[0]*0.8)]]

val_motor_control = motor_control[int_idx[int(int_idx.shape[0]*0.8): int(int_idx.shape[0]*0.9)]]
val_position = position[int_idx[int(int_idx.shape[0]*0.8): int(int_idx.shape[0]*0.9)]]

test_motor_control = motor_control[int_idx[int(int_idx.shape[0]*0.9):]]
test_position = position[int_idx[int(int_idx.shape[0]*0.9):]]

ext_motor_control = motor_control[ext_idx]
ext_position = position[ext_idx]

train_motor_control.shape, val_motor_control.shape, test_motor_control.shape, ext_motor_control.shape

((3160, 3), (395, 3), (395, 3), (1694, 3))

In [51]:
assert len(position.shape) == 3
assert len(motor_control.shape) == 2

dataset_dict = {
    "train":dict(motor_control = train_motor_control.tolist(), position = train_position.tolist()),
    "val": dict(motor_control = val_motor_control.tolist(), position = val_position.tolist()),
    "test": dict(motor_control = test_motor_control.tolist(), position = test_position.tolist()),
    "ext": dict(motor_control = ext_motor_control.tolist(), position = ext_position.tolist())    
}    



In [52]:
import json
with open("ABAQUS.json", 'w') as outfile:
    json.dump(dataset_dict, outfile)


## SOROSIM

In [53]:
np.random.seed(seed)
random.seed(seed)

In [54]:
from pathlib import Path
DATA_PATH =  Path("dataset/SOROSIM1D_DATASET")
int_motor_control, int_position = load_json(DATA_PATH/"SoroSim_Interpolate.json")
ext_motor_control, ext_position = load_json(DATA_PATH/"SoroSim_Extrapolate.json")

int_motor_control.shape, int_position.shape, ext_motor_control.shape, ext_position.shape


((10000, 4), (10000, 9, 3), (5000, 4), (5000, 9, 3))

In [55]:
int_idx = np.arange(len(int_motor_control))
random.shuffle(int_idx)

ext_idx = np.arange(len(ext_motor_control))
random.shuffle(ext_idx)


In [56]:
train_motor_control = int_motor_control[int_idx[:int(int_idx.shape[0]*0.8)]]
train_position = int_position[int_idx[:int(int_idx.shape[0]*0.8)]]

val_motor_control = int_motor_control[int_idx[int(int_idx.shape[0]*0.8): int(int_idx.shape[0]*0.9)]]
val_position = int_position[int_idx[int(int_idx.shape[0]*0.8): int(int_idx.shape[0]*0.9)]]

test_motor_control = int_motor_control[int_idx[int(int_idx.shape[0]*0.9):]]
test_position = int_position[int_idx[int(int_idx.shape[0]*0.9):]]

ext_motor_control = ext_motor_control[ext_idx]
ext_position = ext_position[ext_idx]

In [57]:
assert len(position.shape) == 3
assert len(motor_control.shape) == 2

dataset_dict = {
    "train":dict(motor_control = train_motor_control.tolist(), position = train_position.tolist()),
    "val": dict(motor_control = val_motor_control.tolist(), position = val_position.tolist()),
    "test": dict(motor_control = test_motor_control.tolist(), position = test_position.tolist()),
    "ext": dict(motor_control = ext_motor_control.tolist(), position = ext_position.tolist())    
}    



In [58]:
import json
with open("SOROSIM.json", 'w') as outfile:
    json.dump(dataset_dict, outfile)



## FINGER

In [59]:
np.random.seed(seed)
random.seed(seed)

In [60]:
from pathlib import Path
DATA_PATH =  Path("dataset/FINGER_DATASET")
motor_control, position = load_json(DATA_PATH/"finger_dataset_0904.json")
position = position.reshape(len(position), 1, 3)

motor_control.shape, position.shape

((3399, 4), (3399, 1, 3))

In [61]:
int_ratio = 0.7
sort_idx = np.argsort(np.linalg.norm(motor_control, axis=1))

int_idx = sort_idx[:int(sort_idx.shape[0]*int_ratio)]
ext_idx =sort_idx[int(sort_idx.shape[0]*int_ratio):]
random.shuffle(int_idx)
random.shuffle(ext_idx)

int_idx.shape, ext_idx.shape

((2379,), (1020,))

In [62]:
train_motor_control = motor_control[int_idx[:int(int_idx.shape[0]*0.8)]]
train_position = position[int_idx[:int(int_idx.shape[0]*0.8)]]

val_motor_control = motor_control[int_idx[int(int_idx.shape[0]*0.8): int(int_idx.shape[0]*0.9)]]
val_position = position[int_idx[int(int_idx.shape[0]*0.8): int(int_idx.shape[0]*0.9)]]

test_motor_control = motor_control[int_idx[int(int_idx.shape[0]*0.9):]]
test_position = position[int_idx[int(int_idx.shape[0]*0.9):]]

ext_motor_control = motor_control[ext_idx]
ext_position = position[ext_idx]

train_motor_control.shape, val_motor_control.shape, test_motor_control.shape, ext_motor_control.shape

((1903, 4), (238, 4), (238, 4), (1020, 4))

In [63]:
assert len(position.shape) == 3
assert len(motor_control.shape) == 2

dataset_dict = {
    "train":dict(motor_control = train_motor_control.tolist(), position = train_position.tolist()),
    "val": dict(motor_control = val_motor_control.tolist(), position = val_position.tolist()),
    "test": dict(motor_control = test_motor_control.tolist(), position = test_position.tolist()),
    "ext": dict(motor_control = ext_motor_control.tolist(), position = ext_position.tolist())    
}    



In [64]:
import json
with open("FINGER.json", 'w') as outfile:
    json.dump(dataset_dict, outfile)


## Test Importing

In [65]:
data_path = "./ABAQUS.json"
import json
with open(data_path,'r') as rdata:
    data = json.load(rdata)

In [66]:
data['train']['motor_control']

[[0.043654948472976685, -0.013184720650315285, -0.09616048634052277],
 [-0.3703983426094055, -0.03598137944936752, -0.08599229902029037],
 [-0.6268599033355713, 0.0785117968916893, -0.08921315521001816],
 [-0.5360323190689087, 0.09694831818342209, -0.08995439857244492],
 [0.0007188920280896127, 0.03817679360508919, -0.08605728298425674],
 [-0.21976704895496368, 0.06028833985328674, -0.08949682116508484],
 [0.13003553450107574, -0.0063547189347445965, -0.0822334811091423],
 [-0.33817046880722046, -0.05034250393509865, -0.08023972064256668],
 [-0.4583873450756073, -0.05048804730176926, -0.09874947369098663],
 [-0.5941482186317444, -0.01434986013919115, -0.0860821083188057],
 [-0.54508376121521, -0.04812400043010712, -0.09226617217063904],
 [-0.08450126647949219, -0.07705280929803848, -0.08793435245752335],
 [-0.3691110610961914, -0.08184404671192169, -0.0918523296713829],
 [-0.4440051317214966, 0.05593687295913696, -0.08837190270423889],
 [-0.30452433228492737, 0.0752841904759407, -0.095

In [68]:
import torch
motor_control = torch.tensor(data['train']["motor_control"], dtype=torch.float)
position = torch.tensor(data['train']["position"], dtype=torch.float)

axis_mean_position = torch.mean(position, dim=1)

motor_std, motor_mean = torch.std_mean(motor_control, dim=0)
pos_std, pos_mean = torch.std_mean(axis_mean_position, dim=0)


motor_std, motor_mean, pos_std, pos_mean

(tensor([0.2252, 0.0572, 0.0058]),
 tensor([-2.5645e-01,  1.9985e-04, -8.9954e-02]),
 tensor([39.1355, 39.1476, 17.9328]),
 tensor([-157.7736, -164.7572,  861.0818]))